#version: "3.7"
services:
  postgres_db:
    image: postgres 
    environment:
      POSTGRES_PASSWORD: heslo123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_database
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  python_main:
    build: ./
    command: python3 ./main.py
    depends_on:
      postgres_db:
        condition: service_healthy
    links:
      - postgres_db
    ports:
      - '8080:8080'